---
title: 'GWAS 教程介紹'
author: Francoise
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: false
---

# 歡迎！

歡迎使用這份資源開始學習全基因組關聯研究（Genome Wide Association Studies, GWAS）。

本教程受到[Reed2015](https://dx.doi.org/10.1002/sim.6605)和[Marees2017](https://onlinelibrary.wiley.com/doi/abs/10.1002/mpr.1608)中相似工作的啟發。遺憾的是，2015年的教程所使用的軟件目前略顯過時——部分R包已發生變化或不再提供——因而本教程進行了相應的更新。

本教程共分為四部分：

## [(1) Data Formats, Summary Statistics, and QC](quality_control.html)

該節主要介紹從不同檔案類型到數據初步檢查的基礎知識，以及如何排除可能影響分析結果的數據部分。

## [(2) Imputation](imputation.html)

"Imputation"部分描述了如何通過邏輯方法替換缺失值來處理缺失數據的過程。特別是對於不能處理缺失值的SNP數據分析方法（如回歸分析），必須在分析前解決缺失數據問題。

## [(3) Population Structure](population_structure.html)

"Population Structure"節幫助讀者考慮可能存在於數據集中的潛在混淆因素（例如家族關係）。若不明確進行調整，這些因素可能會錯誤地放大分析結果，從而導致推論偏誤。

## [(4) Analyzing association](analyzing_association.html)

正如其名，"Analyzing association"是GWAS的核心目的。本部分分為兩節，分別為單獨考慮每個SNP的"Marginal"分析和同時考慮所有SNP的"Joint/simultaneous"分析：

- [Marginal](marginal_analysis.html)
- [Joint/simultaneous](joint_analysis.html)

## [Post Analysis](post_gwas.html)

在"Post Analysis"部分，將嘗試將分析結果轉化為臨床上有意義的信息。舉例而言，單純告知某個SNP的信息可能缺乏意義，除非進行了深入研究。相對地，如果指出某個SNP的變異與氯通道的異常功能相關，則更具有臨床意義。
